var attachmentsRiflesUs=[
{name:'none',slot:['Barrel','Accessory']},
{name:'Iron Sights',slot:'Optic'},
{name:'Underslung Rail',slot:'Underbarrel'},
{name:'Reflex (RDS)',slot:'Optic'},
{name:'Laser Sight',slot:'Accessory'},
{name:'ERGO Grip',slot:'Underbarrel'},
{name:'Muzzle Brake',slot:'Barrel'},
{name:'ACOG (4X)',slot:'Optic'},
{name:'Canted Iron Sights',slot:'Accessory'},
{name:'Angled Grip',slot:'Underbarrel'},
{name:'Heavy Barrel',slot:'Barrel'},
{name:'M145 (3.4X)',slot:'Optic'},
{name:'Flash Light',slot:'Accessory'},
{name:'Bipod',slot:'Underbarrel'},
{name:'Compensator',slot:'Barrel'},
{name:'Holo (1X)',slot:'Optic'},
{name:'Magnifier (2X)',slot:'Accessory'},
{name:'Stubby Grip',slot:'Underbarrel'},
{name:'Suppressor',slot:'Barrel'},
];
var attachmentsRiflesRu=[
{name:'none',slot:['Barrel','Accessory']},
{name:'Iron Sights',slot:'Optic'},
{name:'UGL Rail',slot:'Underbarrel'},
{name:'Kobra (RDS)',slot:'Optic'},
{name:'Laser Sight',slot:'Accessory'},
{name:'ERGO Grip',slot:'Underbarrel'},
{name:'Muzzle Brake',slot:'Barrel'},
{name:'PSO-1 (4X)',slot:'Optic'},
{name:'Canted Iron Sights',slot:'Accessory'},
{name:'Angled Grip',slot:'Underbarrel'},
{name:'Heavy Barrel',slot:'Barrel'},
{name:'M145 (3.4X)',slot:'Optic'},
{name:'Flash Light',slot:'Accessory'},
{name:'Bipod',slot:'Underbarrel'},
{name:'Compensator',slot:'Barrel'},
{name:'PKA-S (1X)',slot:'Optic'},
{name:'Magnifier (2X)',slot:'Accessory'},
{name:'Stubby Grip',slot:'Underbarrel'},
{name:'PBS-4 Suppressor',slot:'Barrel'},
];
var attachmentsRiflesCh=[
{name:'none',slot:['Barrel','Accessory']},
{name:'Iron Sights',slot:'Optic'},
{name:'UGL Rail',slot:'Underbarrel'},
{name:'Coyote (RDS)',slot:'Optic'},
{name:'Laser Sight',slot:'Accessory'},
{name:'ERGO Grip',slot:'Underbarrel'},
{name:'Muzzle Brake',slot:'Barrel'},
{name:'JGM-4 (4X)',slot:'Optic'},
{name:'Canted Iron Sights',slot:'Accessory'},
{name:'Angled Grip',slot:'Underbarrel'},
{name:'Heavy Barrel',slot:'Barrel'},
{name:'PRISMA (3.4X)',slot:'Optic'},
{name:'Flash Light',slot:'Accessory'},
{name:'Bipod',slot:'Underbarrel'},
{name:'Compensator',slot:'Barrel'},
{name:'HD-33 (1X)',slot:'Optic'},
{name:'Magnifier (2X)',slot:'Accessory'},
{name:'Stubby Grip',slot:'Underbarrel'},
{name:'LS06 Suppressor',slot:'Barrel'},
];
var attachmentsPdwUs=[
{name:'none',slot:['Barrel','Accessory']},
{name:'Iron Sights',slot:'Optic'},
{name:'Reflex (RDS)',slot:'Optic'},
{name:'Laser Sight',slot:'Accessory'},
{name:'ERGO Grip',slot:'Underbarrel'},
{name:'Muzzle Brake',slot:'Barrel'},
{name:'ACOG (4X)',slot:'Optic'},
{name:'Canted Iron Sights',slot:'Accessory'},
{name:'Angled Grip',slot:'Underbarrel'},
{name:'Heavy Barrel',slot:'Barrel'},
{name:'M145 (3.4X)',slot:'Optic'},
{name:'Flash Light',slot:'Accessory'},
{name:'Bipod',slot:'Underbarrel'},
{name:'Compensator',slot:'Barrel'},
{name:'Holo (1X)',slot:'Optic'},
{name:'Stubby Grip',slot:'Underbarrel'},
{name:'Suppressor',slot:'Barrel'},
];